# Generated by Django 5.1.3 on 2024-11-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_news_options_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='namee',
            new_name='name',
        ),
    ]
